[package]
name = "nimbus"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_egui = "0.30.1"

# How to scale the UI made with bevy_egui
[[example]]
name = "bevy_egui_scaling"
path = "examples/bevy_basic/bevy_egui_scaling.rs"
